---
title: "「子どもの生活と学びに関する親子調査　Wave1～7, 2015-2021」（調査番号：1571）コードブック"
author: "藤原翔（東京大学社会科学研究所）"
format:
    html:
      toc: true
toc-location: right
self-contained: true
scrollable: true
page-layout: full
number-sections: true
code-fold: true
crossref:
  fig-title: Figure     # (default is "Figure")
tbl-title: 変数  # (default is "Table")
title-delim: "　　"     # (default is ":")
execute:
  cache: false
warning: false
message: false
echo: false
date: "`r Sys.Date()`"
editor: source
---

```{r data}
#| echo: false
pacman::p_load(tidyverse, 
               haven, 
               labelled, 
               DT, 
               knitr,
               janitor,
               kableExtra)
d <- read_dta("~/Data/Benesse/1571/1571.dta")
```


# 調査の概要

- 本資料は「子どもの生活と学びに関する親子調査　Wave1～7, 2015-2021」（調査番号：1571）のメタデータより作成した非公式のコードブックです．変数の検索や確認に利用してください．

- 調査の概要については以下を参照してください．
<https://doi.org/10.34500/SSJDA.1571>



# 変数や値ラベルの検索

- 変数名や値ラベルの検索が可能です．ただし，調査票も必ず確認するようにしてください．
- 変数名をクリックすると，その変数の度数分布へ移動します（JLSCP_codebook.htmlというファイル名は変更しないでください）．


```{r search}
#| echo: false
base <- look_for(d) %>% 
  convert_list_columns_to_character() %>% 
  select(2:3,7) %>% 
  rownames_to_column()
base %>% 
  mutate(variable = paste0("<a href = 'JLSCP_codebook.html#tbl-",variable,"'>",variable,"</a>")) %>%
  rename(番号 = rowname,
         変数 = variable,
         変数ラベル = label,
         値ラベル = value_labels) %>%
  datatable(filter = 'top', 
            rownames = FALSE,
            escape = FALSE,
            options = list(
              autoWidth = TRUE,
              columnDefs = list(list(width = '400px', targets = c(2,3)))))
#
```

<!--- --->
  
  
  
# 変数リスト
  
```{r}
#codebook <- map_df(d, function(x) {attributes(x)$label |> str_remove_all("\\n")}) %>% 
#  gather(key = Code, value = Label)
#codebook %>% select(変数 = Code, 変数ラベル = Label) |> kable()

codebook <- map_df(d, function(x) {
  attributes(x)$label |> str_remove_all("\\n")
}) %>%
  gather(key = Code, value = Label) %>%
  mutate(Code = paste0(
    "<a href='JLSCP_codebook.html#tbl-", Code, "'>", Code, "</a>"
  ))

codebook %>%
  select(変数 = Code, 変数ラベル = Label) %>%
  kable(escape = FALSE)
```



```{r}
temp <- function(i){
  d %>%
    data.frame %>%
    transmute(value = .[, i], 
              label = as_factor(.[, i])) %>%
    tibble() %>%
    count(value, label) %>%
    ungroup() %>%
    mutate(値 = value,
           値ラベル = label,
           `％` = n / sum(n) * 100,
           `有効％` = case_when(
             is.na(値) ~ NA,
             TRUE ~ n / sum(n[!is.na(値)]) * 100)
    ) %>%
    select(値, 値ラベル, n, `％`, `有効％`) %>%
    adorn_totals(name = "全体") |> 
    tibble() %>%
    knitr::kable(
      digit = 1,
      format = "simple",
      label = NA,
      caption = paste0(
        i,
        "：",
        var_label(d[, i]) |> str_remove_all("\\n"),
        " {#tbl-",
        i,
        "}"
      ),
      align = "rlrr"
    ) %>%
    print()
  cat('\n\n<!-- -->\n\n')
}
```



# 変数の値，ラベル，度数分布

- 各変数の度数分布表です．
- 無回答と非該当の区別はしていないことに注意してください．


```{r function_temp}
#| echo: false
temp <- function(i){
  d %>% 
    data.frame %>%
    transmute(value = .[,i] %>% factor() %>% fct_explicit_na(),
              label = as_factor(.[,i])) %>%
    tibble() %>%
    group_by(value,label) %>%
    count()  %>% 
    ungroup() %>%
    mutate(percent = n / sum(n) * 100)%>%
    select(値 = value, 値ラベル = label, 度数 = n, パーセント = percent) %>%
    tibble() %>%
    knitr::kable(digit = 1,
                 format = "simple",
                 caption = paste0(i,"：",var_label(d[,i])," {#tbl-",i,"}"),
                 align = "rlrr"
    ) %>%
    kable_styling(full_width = FALSE) %>% 
    column_spec(column = 1:4, width = "1.5in", bold = TRUE, italic = TRUE) %>% print()
  cat('\n\n<!-- -->\n\n')
}
```

```{r, results = "asis"}
#| echo: false
names(d)[! names(d) %in% c("PanelID")] %>% walk(~temp(.x))
```
